### PR TITLE
Fix code snippet paths

### PR DESCRIPTION
**Pull request by SimonMarquis**
~~Fixes missing code snippet in https://gradlex.org/build-parameters/#disable-build-parameter-validation~~

### CODE REVIEW

**Review by britter — CHANGES_REQUESTED** [review]
Thank you for bringing this to our attention. Unfortunately I think this is the "wrong" fix. The paths to the build files are incorrect in index.adoc and that needs to be fixed. Otherwise we would include the wrong build files into the documentation. The tags need to stay.

```diff
────────────────────────────────────────────────────────────────────────────────
modified: src/docs/asciidoc/index.adoc
────────────────────────────────────────────────────────────────────────────────
@ src/docs/asciidoc/index.adoc:330 @ If you do not want this validation in your build, you can disable it.

[source.multi-language-sample,kotlin]
----
-- include::{samples-path}/validation/kotlin/build.gradle.kts[tags=disable-validation]
++ include::{samples-path}/validation/kotlin/gradle/plugins/build-parameters/build.gradle.kts[tags=disable-validation]
----
[source.multi-language-sample,groovy]
----
-- include::{samples-path}/validation/groovy/build.gradle[tags=disable-validation]
++ include::{samples-path}/validation/groovy/gradle/plugins/build-parameters/build.gradle[tags=disable-validation]
----
```

**Comment by SimonMarquis** [comment]
Oh indeed that not the expected paths. Do you prefer opening a new PR or simply updating this one?

**Comment by britter** [comment]
I don't mind :o)

**Comment by SimonMarquis** [comment]
I've update the PR

**Review by britter — APPROVED** [review]

**Pull request merged**
